# Generated by Django 3.2.17 on 2023-02-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
