# Generated by Django 3.2.17 on 2023-02-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230218_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn13',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
