# Generated by Django 3.2.17 on 2023-02-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_isbn13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
